import 'package:flutter/material.dart';

class Contant {
  int id;
  String image;
  String title;
  double point;
  double count = 0;
  Contant(
      {required this.id,
      required this.image,
      required this.title,
      required this.point,
      required this.count});
}

List plastic_contant = [
  Contant(
      id: 1,
      image: "assets/image/plastictab/images (1).jpg",
      title: "bottles",
      point: 0.76,
      count: 0),
  Contant(
      id: 2,
      image: "assets/image/plastictab/27181.jpg",
      title: "Big bottle",
      point: 23.75,
      count: 0),
  Contant(
      id: 3,
      image: "assets/image/plastictab/9yes_e9cf_140728.jpg",
      title: "chair",
      point: 190,
      count: 0),
  Contant(
      id: 4,
      image: "assets/image/plastictab/collection-three-shampoo-container.jpg",
      title: "Shampoo bottles",
      point: 0.57,
      count: 0),
  // Contant(
  //     id: 5,
  //     image:
  //         "assets/image/electronicstab/43.jpg",
  //     title: "plastics",
  //     point: 0.76,
  //     count: 0),
  Contant(
      id: 7,
      image: "assets/image/plastictab/3392.jpg",
      title: "jerry cans",
      point: 3.8,
      count: 0),
  Contant(
      id: 8,
      image: "assets/image/plastictab/baby.jpg",
      title: "Baby Gears",
      point: 190,
      count: 0),
  Contant(
      id: 9,
      image: "assets/image/plastictab/images (2).jpg",
      title: "colman water",
      point: 152,
      count: 0),
  Contant(
      id: 10,
      image: "assets/image/plastictab/download.jpg",
      title: "Artificial grass",
      point: 13.3,
      count: 0),
  Contant(
      id: 11,
      image: "assets/image/plastictab/871.jpg",
      title: "Plastic Battel",
      point: 570,
      count: 0),
  Contant(
      id: 12,
      image: "assets/image/plastictab/images.jpg",
      title: "child bicycle",
      point: 228,
      count: 0),
];

List paper_contant = [
  Contant(
      id: 1,
      image: "assets/image/papertab/collection of books.jpg",
      title: "Books",
      point: 47.5,
      count: 0),
  Contant(
      id: 2,
      image: "assets/image/papertab/magazine.jpg",
      title: "newspaper",
      point: 57,
      count: 0),
  Contant(
      id: 3,
      image: "assets/image/papertab/cardboard box.jpg",
      title: "cardboard",
      point: 33.25,
      count: 0),
  Contant(
      id: 4,
      image: "assets/image/papertab/copybooks.jpg",
      title: "magazines",
      point: 19,
      count: 0),
  Contant(
      id: 5,
      image: "assets/image/papertab/download.jpg",
      title: "paper",
      point: 47.5,
      count: 0),
  Contant(
      id: 6,
      image: "assets/image/papertab/download (1).jpg",
      title: "shredded",
      point: 14.25,
      count: 0),
];

List cooking_contant = [
  Contant(
      id: 1,
      image: "assets/image/cookingoiltab/cooking oil.jpg",
      title: "used coooking",
      point: 190,
      count: 0),
];

List electronics_contant = [
  Contant(
      id: 1,
      image: "assets/image/electronicstab/44.jpg",
      title: "mobile",
      point: 285,
      count: 0),
  Contant(
      id: 2,
      image: "assets/image/electronicstab/43.jpg",
      title: "laptob",
      point: 760,
      count: 0),
  Contant(
      id: 3,
      image: "assets/image/electronicstab/3.jpg",
      title: "Router",
      point: 95,
      count: 0),
  Contant(
      id: 4,
      image: "assets/image/electronicstab/5.jpg",
      title: "LED TV",
      point: 760,
      count: 0),
  Contant(
      id: 5,
      image: "assets/image/electronicstab/10.jpg",
      title: "computer monitor",
      point: 380,
      count: 0),
  Contant(
      id: 7,
      image: "assets/image/electronicstab/6.jpg",
      title: "computer CPU",
      point: 570,
      count: 0),
  Contant(
      id: 8,
      image: "assets/image/electronicstab/8.jpg",
      title: "Receiver",
      point: 285,
      count: 0),
  Contant(
      id: 9,
      image: "assets/image/electronicstab/20.jpg",
      title: "Laptop battery",
      point: 57,
      count: 0),
  Contant(
      id: 10,
      image: "assets/image/electronicstab/22.jpg",
      title: "Printer ",
      point: 380,
      count: 0),
  Contant(
      id: 11,
      image: "assets/image/electronicstab/23.jpg",
      title: "scanner",
      point: 285,
      count: 0),
  Contant(
      id: 12,
      image: "assets/image/electronicstab/5.jpg",
      title: "subwoofer",
      point: 76,
      count: 0),
  Contant(
      id: 13,
      image: "assets/image/electronicstab/7.jpg",
      title: "memory ram",
      point: 57,
      count: 0),
  Contant(
      id: 14,
      image: "assets/image/electronicstab/30.jpg",
      title: "power supply",
      point: 95,
      count: 0),
  Contant(
      id: 15,
      image: "assets/image/electronicstab/26.jpg",
      title: "screen card",
      point: 38,
      count: 0),
  Contant(
      id: 16,
      image: "assets/image/electronicstab/38.jpg",
      title: "printing machine",
      point: 570,
      count: 0),
  Contant(
      id: 17,
      image: "assets/image/electronicstab/16.jpg",
      title: "mobile motherboard",
      point: 57,
      count: 0),
  Contant(
      id: 18,
      image: "assets/image/electronicstab/44.jpg",
      title: "laptop motherboard",
      point: 95,
      count: 0),
  Contant(
      id: 19,
      image: "assets/image/electronicstab/31.jpg",
      title: "playStation1",
      point: 285,
      count: 0),
  Contant(
      id: 20,
      image: "assets/image/electronicstab/21.jpg",
      title: "DVD player",
      point: 133,
      count: 0),
  Contant(
      id: 21,
      image: "assets/image/electronicstab/29.jpg",
      title: "vidio device",
      point: 95,
      count: 0),
  Contant(
      id: 22,
      image: "assets/image/electronicstab/34.jpg",
      title: "microphone",
      point: 190,
      count: 0),
  Contant(
      id: 23,
      image: "assets/image/electronicstab/33.jpg",
      title: "pc fan",
      point: 4.75,
      count: 0),
  Contant(
      id: 24,
      image: "assets/image/electronicstab/11.jpg",
      title: "processor",
      point: 19,
      count: 0),
  Contant(
      id: 25,
      image: "assets/image/electronicstab/22.jpg",
      title: "CD rom drive",
      point: 38,
      count: 0),
  Contant(
      id: 26,
      image: "assets/image/electronicstab/6.jpg",
      title: "airpods",
      point: 95,
      count: 0),
  Contant(
      id: 27,
      image: "assets/image/electronicstab/3.jpg",
      title: "shaver",
      point: 95,
      count: 0),
  Contant(
      id: 28,
      image: "assets/image/electronicstab/3.jpg",
      title: "sound card",
      point: 76,
      count: 0),
  Contant(
      id: 29,
      image: "assets/image/electronicstab/37.jpg",
      title: "Network card",
      point: 76,
      count: 0),
  Contant(
      id: 30,
      image: "assets/image/electronicstab/17.jpg",
      title: "camera",
      point: 76,
      count: 0),
  Contant(
      id: 31,
      image: "assets/image/electronicstab/27.jpg",
      title: "Hard disk",
      point: 95,
      count: 0),
  Contant(
      id: 32,
      image: "assets/image/electronicstab/35.jpg",
      title: "Hoverboard",
      point: 380,
      count: 0),
  Contant(
      id: 33,
      image: "assets/image/electronicstab/38.jpg",
      title: "radio sound",
      point: 285,
      count: 0),
  Contant(
      id: 35,
      image: "assets/image/electronicstab/29.jpg",
      title: "piano",
      point: 950,
      count: 0),
  Contant(
      id: 36,
      image: "assets/image/electronicstab/24.jpg",
      title: "projector",
      point: 950,
      count: 0),
  Contant(
      id: 37,
      image: "assets/image/electronicstab/9.jpg",
      title: "mifi",
      point: 285,
      count: 0),
  Contant(
      id: 38,
      image: "assets/image/electronicstab/16.jpg",
      title: "Car Vacuum Cleaner",
      point: 190,
      count: 0),
  Contant(
      id: 39,
      image: "assets/image/electronicstab/13.jpg",
      title: "power Bank",
      point: 95,
      count: 0),
  Contant(
      id: 40,
      image: "assets/image/electronicstab/12.jpg",
      title: "Usb Modem",
      point: 95,
      count: 0),
  Contant(
      id: 41,
      image: "assets/image/electronicstab/18.jpg",
      title: "Wii",
      point: 570,
      count: 0),
  Contant(
      id: 42,
      image: "assets/image/electronicstab/42.jpg",
      title: "playstation2",
      point: 760,
      count: 0),
  Contant(
      id: 43,
      image: "assets/image/electronicstab/40.jpg",
      title: "XBox",
      point: 760,
      count: 0),
];

List metals_contant = [
  Contant(
      id: 1,
      image: "assets/image/metalstab/download (24).jpg",
      title: "cans",
      point: 3.42,
      count: 0),
  Contant(
      id: 2,
      image: "assets/image/metalstab/51iLHmUdt1L.jpg",
      title: "copper",
      point: 950,
      count: 0),
  Contant(
      id: 3,
      image: "assets/image/metalstab/download.jpg",
      title: "Basin mixer",
      point: 95,
      count: 0),
  Contant(
      id: 4,
      image: "assets/image/metalstab/amunim.jpg",
      title: "Auminium",
      point: 513,
      count: 0),
  Contant(
      id: 5,
      image: "assets/image/metalstab/images.jpg",
      title: "cooking pan",
      point: 152,
      count: 0),
  Contant(
      id: 7,
      image: "assets/image/metalstab/download (1).jpg",
      title: "Fire extinguisher",
      point: 57,
      count: 0),
  Contant(
      id: 8,
      image: "assets/image/metalstab/images (1).jpg",
      title: "Iron",
      point: 76,
      count: 0),
  Contant(
      id: 9,
      image: "assets/image/metalstab/images (2).jpg",
      title: "Tinplate",
      point: 0.38,
      count: 0),
  Contant(
      id: 10,
      image: "assets/image/metalstab/download (2).jpg",
      title: "Door handeliers",
      point: 28.5,
      count: 0),
  Contant(
      id: 11,
      image: "assets/image/metalstab/images (3).jpg",
      title: "Chandeliers",
      point: 190,
      count: 0),
  Contant(
      id: 12,
      image: "assets/image/metalstab/download (3).jpg",
      title: "scooter",
      point: 95,
      count: 0),
  // Contant(
  //     id: 13,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Clothes dryer",
  //     point: 190,
  //     count: 0),
  // Contant(
  //     id: 14,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Alumetal",
  //     point: 1140,
  //     count: 0),
  // Contant(
  //     id: 15,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Washing Machine Base",
  //     point: 190,
  //     count: 0),
  // Contant(
  //     id: 16,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Water motor",
  //     point: 1520,
  //     count: 0),
  // Contant(
  //     id: 17,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Trans",
  //     point: 38,
  //     count: 0),
  // Contant(
  //     id: 18,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Balloon Motor",
  //     point: 114,
  //     count: 0),
  // Contant(
  //     id: 19,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Pan",
  //     point: 95,
  //     count: 0),
  // Contant(
  //     id: 20,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Granite Pot",
  //     point: 190,
  //     count: 0),
  // Contant(
  //     id: 21,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Stainless Sink",
  //     point: 665,
  //     count: 0),
  // Contant(
  //     id: 22,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Tire Rim",
  //     point: 304,
  //     count: 0),
  // Contant(
  //     id: 23,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Cans",
  //     point: 285,
  //     count: 0),
  // Contant(
  //     id: 24,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Ladder",
  //     point: 380,
  //     count: 0),
  // Contant(
  //     id: 25,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Stainless",
  //     point: 57,
  //     count: 0),
  // Contant(
  //     id: 26,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Tinplate",
  //     point: 19,
  //     count: 0),
  // Contant(
  //     id: 27,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Office Chair",
  //     point: 380,
  //     count: 0),
  // Contant(
  //     id: 28,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Fridge Motor",
  //     point: 950,
  //     count: 0),
  // Contant(
  //     id: 29,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Washing Motor",
  //     point: 950,
  //     count: 0),
];

List home_contant = [
  Contant(
      id: 1,
      image: "assets/image/homeappliancestab/download.jpg",
      title: "Fan",
      point: 380,
      count: 0),
  Contant(
      id: 2,
      image: "assets/image/homeappliancestab/download (17).jpg",
      title: "Iron",
      point: 190,
      count: 0),
  Contant(
      id: 3,
      image: "assets/image/homeappliancestab/images.jpg",
      title: "Gas Heater",
      point: 1140,
      count: 0),
  Contant(
      id: 4,
      image: "assets/image/homeappliancestab/images (1).jpg",
      title: "Air Conditioner",
      point: 4750,
      count: 0),
  Contant(
      id: 5,
      image: "assets/image/homeappliancestab/download (1).jpg",
      title: "Blender,",
      point: 228,
      count: 0),
  Contant(
      id: 7,
      image: "assets/image/homeappliancestab/download (2).jpg",
      title: "Microwave",
      point: 667,
      count: 0),
  Contant(
      id: 8,
      image: "assets/image/homeappliancestab/download (3).jpg",
      title: "Fridge",
      point: 3800,
      count: 0),
  Contant(
      id: 9,
      image: "assets/image/homeappliancestab/download (4).jpg",
      title: "Washer",
      point: 2470,
      count: 0),
  Contant(
      id: 10,
      image: "assets/image/homeappliancestab/images (2).jpg",
      title: "Vacuum",
      point: 475,
      count: 0),
  // Contant(
  //     id: 11,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Kattle",
  //     point: 76,
  //     count: 0),
  // Contant(
  //     id: 12,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Chopper",
  //     point: 57,
  //     count: 0),
  // Contant(
  //     id: 13,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Heater Device",
  //     point: 190,
  //     count: 0),
  // Contant(
  //     id: 14,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Radio",
  //     point: 95,
  //     count: 0),
  // Contant(
  //     id: 15,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Cooker",
  //     point: 1900,
  //     count: 0),
  // Contant(
  //     id: 16,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Dish Washer",
  //     point: 1425,
  //     count: 0),
  // Contant(
  //     id: 17,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Electric fryer",
  //     point: 285,
  //     count: 0),
  // Contant(
  //     id: 18,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Ventilation fan",
  //     point: 285,
  //     count: 0),
  // Contant(
  //     id: 19,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "kitchen machine",
  //     point: 228,
  //     count: 0),
  // Contant(
  //     id: 20,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Mixer",
  //     point: 95,
  //     count: 0),
  // Contant(
  //     id: 21,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "toster",
  //     point: 190,
  //     count: 0),
  // Contant(
  //     id: 22,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Hair dryer",
  //     point: 95,
  //     count: 0),
  // Contant(
  //     id: 23,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Babyliss",
  //     point: 95,
  //     count: 0),
  // Contant(
  //     id: 24,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Insect Killer",
  //     point: 190,
  //     count: 0),
  // Contant(
  //     id: 25,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Electric fly insect killer",
  //     point: 38,
  //     count: 0),
  // Contant(
  //     id: 26,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Led Rechargeable",
  //     point: 76,
  //     count: 0),
  // Contant(
  //     id: 27,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Digital clock",
  //     point: 57,
  //     count: 0),
  // Contant(
  //     id: 28,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Treadmill",
  //     point: 2850,
  //     count: 0),
  // Contant(
  //     id: 29,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Iron table",
  //     point: 133,
  //     count: 0),
  // Contant(
  //     id: 30,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "DeepFreezer",
  //     point: 1710,
  //     count: 0),
  // Contant(
  //     id: 31,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Steam iron",
  //     point: 285,
  //     count: 0),
  // Contant(
  //     id: 32,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Hand biender",
  //     point: 152,
  //     count: 0),
  // Contant(
  //     id: 33,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Coffee maker",
  //     point: 285,
  //     count: 0),
  // Contant(
  //     id: 34,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Camera",
  //     point: 190,
  //     count: 0),
  // Contant(
  //     id: 35,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Blower",
  //     point: 190,
  //     count: 0),
  // Contant(
  //     id: 36,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Tea thermos",
  //     point: 133,
  //     count: 0),
  // Contant(
  //     id: 37,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Lamp shades",
  //     point: 95,
  //     count: 0),
  // Contant(
  //     id: 38,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Sandwich maker",
  //     point: 190,
  //     count: 0),
  // Contant(
  //     id: 39,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Theatre Home Sound",
  //     point: 2850,
  //     count: 0),
  // Contant(
  //     id: 40,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Grill",
  //     point: 190,
  //     count: 0),
  // Contant(
  //     id: 41,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Mini bar fridge",
  //     point: 570,
  //     count: 0),
  // Contant(
  //     id: 42,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "orbitrack",
  //     point: 1330,
  //     count: 0),
  // Contant(
  //     id: 43,
  //     image: "assets/image/electronicstab/43.jpg",
  //     title: "Sewing machine",
  //     point: 285,
  //     count: 0),
];

List spareparts = [
  Contant(
      id: 1,
      image: "assets/image/sparepartstab/download (1).jpg",
      title: "Car door",
      point: 380,
      count: 0),
  Contant(
      id: 2,
      image: "assets/image/sparepartstab/images.jpg",
      title: "Cabot",
      point: 418,
      count: 0),
  Contant(
      id: 3,
      image: "assets/image/sparepartstab/download.jpg",
      title: "Car Battery",
      point: 1330,
      count: 0),
  Contant(
      id: 4,
      image: "assets/image/sparepartstab/download (2).jpg",
      title: "Radiator",
      point: 475,
      count: 0),
  Contant(
      id: 5,
      image: "assets/image/sparepartstab/download (3).jpg",
      title: "Car Casette",
      point: 190,
      count: 0),
  Contant(
      id: 7,
      image: "assets/image/sparepartstab/download (4).jpg",
      title: "Dynamo",
      point: 380,
      count: 0),
  Contant(
      id: 8,
      image: "assets/image/sparepartstab/images (1).jpg",
      title: "Assistant",
      point: 133,
      count: 0),
  Contant(
      id: 9,
      image: "assets/image/sparepartstab/download (5).jpg",
      title: "Brake Pads",
      point: 152,
      count: 0),
  Contant(
      id: 10,
      image: "assets/image/sparepartstab/images (2).jpg",
      title: "Ignition Coil",
      point: 190,
      count: 0),
  Contant(
      id: 11,
      image: "assets/image/sparepartstab/images (3).jpg",
      title: "Shacman",
      point: 380,
      count: 0),
  Contant(
      id: 12,
      image: "assets/image/sparepartstab/download (6).jpg",
      title: "motorcycle battery",
      point: 855,
      count: 0),
  // Contant(
  //     id: 13,
  //     image: "assets/image/sparepartstab/43.jpg",
  //     title: "Clothes dryer",
  //     point: 665,
  //     count: 0),
];
